# 异步

## 概念

JavaScript是通过事件轮询的方式来实现异步，事件循环的核心是回调函数。Promise是一个异步问题同步化解决方案，目的为了把异步任务(如`ajax`请求)，实现同步化之后避免会堵塞后面的程序并拿到结果，顺便解决回调地狱。

执行机制是会通过调用异步线程，事件被触发时把对应的回调函数推入到回调队列中，当主线程任务执行结束后将回调队列里的任务推入主线程中执行。

## 回调问题

回调函数存在的弊端是无法知道何时推入任务队列，也同时存在回调地狱写法的问题，使代码难以理解和几乎无法拓展。在`try...catch`捕获异常时，只能捕获同步代码的异常，异步代码是无法捕获异常的。回调函数同步并发异步代码的问题和写法上非常的笨重。

```
fs.readFile('./name.text', 'utf-8', (err, data) => {
  if(data){
    fs.readFile('./name.text', 'utf-8', (err, data) => {
       ...
    }
  }
})
```



## 回调管理

回调函数管理的事情，决定哪个回调优先执行，或执行回调的次数等。ES6和Promise之前的解决方案之一是jQuery中有一个专门管理回调列表的方法是`$.Callbacks()`创建一个回调列表，给方法添加相应的函数时可以通过一系列的方法(如`add`，`disable`，`disabled`，`empty`，`fire`，`has`，`lock`，`remove`等)去管理。到演变成`$.Deferred()`方法返回一个`promise`对象包含`resolve`，`reject`等方法。



## Promise由来

随着jQuery中`$.deferred()`方法发展，有一个社区发起了一种叫`Promise A+`的规范，说明实际上有许多库基于规范也有实现Promise对象，并且定义相应的属性方法，最后被新增至ES6中。







## Promise

Promise是一个对象容器，存放的是一个以后才会结束的事件，如异步操作。如日常生活中的收据或小票就相当于一个承诺，未来**一定会**完成的事情。在承诺兑现之前可以做许多的事情，如在`excutor`函数内部定义各种条件，当符合条件时执行`resolve`方法并向外抛出获取的结果，当不符合条件时执行`reject`方法向外抛出错误原因。



尝试打印Promise。发现它是一个系统内置的构造函数。

```
console.log(Promise); //ƒ Promise()
```



试打印`new Promise()`，它接收一个叫`executor`执行者的函数`(resolve, reject) => {...}`。执行者函数也有两个函数参数分别是`resolve`和`reject`。返回了一个`promise`实例对象。

```
console.log(new Promise(function (resolve, reject) { }));

/**
 * Promise {<pending>}
 *   __proto__: Promise
 *   [[PromiseState]]: "pending"
 *   [[PromiseResult]]: undefined
 */
```



`new Promise`是一个同步执行的操作。

```
new Promise(function (resolve, reject) {
  console.log('111');
})
console.log('222');
//先打印111，后222
```



Promise本身是一个异步的操作，**异步操作的特征**有：

- 特征一具有共有的状态，且状态不受外界影响，唯一可以影响变化的是代表异步事件。
  - 进行中 - `pending `
  - 已成功 - `fullfilled(resolve)`
  - 已失败 - `reject`
- 特征二是一个状态过渡至另一个状态，状态的不可逆性。`promise`固化以后，再对`promise`对象添加回调，是可以拿到结果的，但如果事件被触发过了，就错过了。

***同步执行的代码如何异步表现操作呢？***

执行`executor`函数里第一个参数(`resolve`)或第二个参数(`reject`)改变状态为`fulfilled`/`reject`，当执行`resolve()`/`reject()`之后，执行绑定的成功/失败后所对应的回调函数。最后绑定的回调函数可以通过Promise实例对象里的`then()`方法来写成功/失败后的程序

```
let promise = new Promise(function(resolve,reject){
  Math.random() * 100 > 60 
    ? resolve('ok') 
    : reject('no'); 
});

//promise.then(注册成功的回调函数，注册失败的回调函数);
promise.then(
  //注册绑定
  (val)=>{console.log(val)}, 
  (err)=>{console.log(err)}
);
```







## 执行顺序

当在`executor`函数中直接执行异步的`resolve`的函数时，执行顺序是优先执行同步代码，再执行异步代码。

```
let promise = new Promise(function (resolve, reject) {
  console.log('111'); //同步代码
  resolve('333'); //异步代码
})

promise.then((data) => console.log(data)) //异步代码触发resolve执行
console.log('222'); //同步代码
//打印111,222,333
```

当存在微任务时，会优先执行微任务。

```
let promise = new Promise(function (resolve, reject) {
  console.log('111'); //同步代码
  resolve('333'); //异步代码
});

setTimeout(function(){ console.log('setTime') }) //宏任务

//异步代码触发resolve执行
promise.then((data) => console.log(data)) 
console.log('222'); //同步代码

//打印111,222,333,setTime
```



***`Promise`是如何设计的？***

设计为`Promise`执行是同步而`promise.then()`是异步执行的。



***为什么`Promise`执行是同步而`promise.then()`是异步执行的？***

如果`promise.then()`是同步执行时是不合理的，且会阻塞下面程序的执行。



## 宏任务微任务

在JavaScript异步代码中，存在宏任务队列和微任务队列。

- 宏任务：
  - 同步代码
  - 定时器(`setTimeout,setInterval,setImmediate`)
  - 回调函数
  - Ajax
  - DOM事件绑定
- 微任务：
  - `promise.then()`,
  - `promise.catch()`
  - `promise.finally()`
  - `node`中的`process.nextTick()`



## 执行机制

在每一次事件轮询的时候，当主线程中的全部任务都执行完时，此时需要调用任务队列中的回调函数并将其推入执行栈中。此时，会存在优先权的问题，优先放入当前的微任务队列中的回调函数。

即同步任务先执行，然后事件轮询，轮询时查看是否有微任务，有时优先执行微任务里的回调函数，等待微任务执行完毕再执行宏任务。



**宏任务和微任务之间的嵌套处理顺序**

`Promise.resolve()`是调用该构造函数里的`resolve`方法，并执行`then`方法相当于绑定一个成功的回调函数。

分析过程：

1. 第一轮循环，同步任务执行，然而并没有同步任务，走下一步。
2. 遇到微任务`Promise.resolve().then`和宏任务`setTimeout`，优先执行微任务，打印`promise1`。往下执行。
3. 遇到第一个异步任务`setTimeout`，将回调函数挂起并不会执行，此时微任务1的所有代码已经执行完毕。
4. 遇到第二个异步任务`setTimeout`并执行，打印`setTimeout1`。
5. 第二轮循环，遇见并优先执行微任务2`Promise.resolve().then`，打印`promise2`。
6. 最后打印之前挂起后的宏任务回调，打印`setTimeout2`。

```
//微任务1
Promise.resolve().then(() => {
  console.log('promise1');
  //宏任务
  setTimeout(() => {
    console.log('setTimeout2');
  })
})

//宏任务
setTimeout(() => {
  console.log('setTimeout1');
  //微任务2
  Promise.resolve().then(() => {
    console.log('promise2');
  })
})

//打印结果：
//promise1
//setTimeout1
//promise2
//setTimeout2
```



## 链式调用

***链式调用会存在什么问题？***

链式调用中的参数传递。不管成功或失败，只能拿到第一次的结果。

```
let promise = new Promise(function (resolve, reject) {
  resolve('ok');
  resolve('second ok');
})

promise
  .then((data) => console.log(data)) //ok
  .then((data2) => console.log('then2: ' + data2)) //then2: undefined
//说明只能通过第一次then拿到resolve()传入的数据，第二次then却拿不到数据(包括成功/失败)
```

那么如何拿到第二次结果，通过手动在第一次`then()`回调函数里`return`数据。说明了第一次`then`的返回值作为下一次`then`的参数。

```
promise
  .then((data) => {
    console.log(data);
    return 'nice';
  }); 
  //ok
  
  .then((data2) => console.log('then2:' + data2)) 
  //then2:nice
```

既然第一次`then`的返回值作为下一次`then`的参数，那么可以将返回值设定为`new Promise()`，并传入`executor`回调且调用`resolve()`传入参数。

```
promise
//备注：reject()跟resolve()操作一样，不做演示
  .then((data) => {
    console.log(data);
    return new Promise((resolve, reject) => {
      resolve('第二次then得到的参数');
    });
  }) //打印：ok
  
  .then((data2) => console.log('then2:' + data2))
  //打印:then2: 第二次then得到的参数
```

## 状态

Promise具有三个状态，`pending`，`fulfilled`，`rejected`。不会受外界影响，状态一旦发生改变就会固化。假如在`exector`函数内部抛出错误，状态就会更改为`rejected`。



## 异常捕获

问题1：遇到错误的情况是`resolve()`传入未定义的变量导致走`then()`第二个函数打印错误，`executor`回调函数抛出的错误被`then()`里的错误函数马上捕获。

```
let promise = new Promise((resolve, reject) => {
  resolve(a);
});

promise.then(
    (val) => console.log('resolve: ', val),
    (err) => console.log('reject: ', err)
)

//reject: ReferenceError: a is not defined
```

只捕捉错误的写法。

```
//写法一：
promise.then(null, (err) => console.log(err));

//写法二：
promise.catch((err) => console.log(err));
```

由上面的写法延申为以下的写法：

```
//推荐写法：适用于成功/失败的情况
promise
  .then(() => {})
  .catch(() => {})
```



问题2：一旦固化，状态不再改变。执行`resolve()`意味着固化了状态，说明状态固化了只打印`resolve`的值而不是捕获错误。

```
let promise = new Promise((resolve, reject) => {
  //状态：成功
  resolve('success');
  //未定义变量抛出错误
  console.log(a);
})

promise
  .then((val) => console.log(val))
  .catch((err) => console.log(err))

//打印：success
```



问题3：链式调用注入数据有可能导致数据丢失，不管`catch()`前面有多少个`then()`，一旦出现错误都能捕获到(冒泡特性)，`then()`不传数据会丢失数据，冒泡特性，状态固定后无法捕获错误。

```
promise
  .then(() => {})
  .then()
  .then()
  .catch(() => {})
```

```
const p1 = new Promise((resolve, reject) => {
  resolve(new Promise((resolve, reject) => {
    reject('error');
  }))
});
```

问题4：每一个`promise`代表的是一个异步操作，每一个异步操作都有它相应的状态，多个`promise`嵌套下，状态是如何传递的？先执行的固化成功状态后执行`reject()`会冲突吗？

当此时第一个异步操作的结果是返回另一个异步操作时。

```
const p1 = new Promise((resolve, reject) => {});
const p1 = new Promise((resolve, reject) => {
  resolve(p1);
});
```

当3秒后会更改`p1`的状态为失败态，1秒后更改`p2`的状态为成功态，但其实`p2`的状态已经固化为成功态了，然后`resolve`了`p1`的`reject`。在`p2`依赖了`p1`的结果冲突的情况下，会导致`p2`的状态失效。

```
const p1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject('error');
  }, 3000)
});

const p2 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(p1);
  }, 1000);
});

p2
  .then(res=>console.log(res))
  .catch(err=>console.log(err));
```



## 异步关系管理

在jQuery中通过`callbacks`的方式来管理回调函数。Promise管理当前回调异步的一些关系，原型上的`catch`，`then`，`finally`方法，静态方法有`all`，`race`，`reject`，`resolve`方法。其中`all`和`race`是管理异步关系的。

- `Promise.all()`：管理多个`promise`实例对象并包装成一个新的实例。
- `Promise.race()`：管理多个`promise`实例对象并包装成一个新的实例，并返回第一个返回的数据。

```
//Promise.all()处理多个Promise异步操作且拿到多个Promise所返回的值
//以数组或具有iterator数据接口方式传多个值

const fs = require('fs');

let p1 = new Promise((resolve, reject) => {
  fs.readFile('./name.txt', 'utf-8', (err, data) => {
    //更改为成功状态并把读取到的data传入
    resolve(data);
  });
});

let p2 = new Promise((resolve, reject) => {
  fs.readFile('./number.txt', 'utf-8', (err, data) => {
    //更改为成功状态并把读取到的data传入
    resolve(data);
  });
});

let p3 = new Promise((resolve, reject) => {
  fs.readFile('./score.txt', 'utf-8', (err, data) => {
    //更改为成功状态并把读取到的data传入
    resolve(data);
  });
});

//拿到成功的结果
const p = Promise.all([p1, p2, p3]);
console.log(p);
//打印一个Promise{}对象
p.then((res) => console.log(res));
// ['./name.txt','./number.txt','./score.txt']

//总结：Promise.all()一旦出现出错，返回第一个出错的报错(不演示)
```

##  `Promise.resolve`

`Promise.resolve`方法，接受一个`thenable`方法部署的对象作为参数，如果该对象有`then`方法时可以直接返回一个`promise`对象。将相应的值转换为一个`promise`对象。场景是将一个异步方法转为`promise`。

```
let thenable = {
  then: function (resolve, reject) {
    resolve(11);
  },
};

//返回了一个promise对象
let p1 = Promise.resolve(thenable);
p1.then((res) => console.log(res)); //11
```

当没有传参时，没有结果。

```
let p1 = Promise.resolve();
p1.then((res) => console.log(res)); //undefined
```

当传入原始值时，返回原始值。

```
let p1 = Promise.resolve('111');
p1.then((res) => console.log(res)); //111
console.log(p1); //Promise {<fulfilled>: '111'}
```



## Promisify

`Promise`化，通过`new Promise`方式将异步操作包装一下。

```
function readFile(path) {
  return new Promise((resolve, reject) => {
    fs.readFile(path, 'utf-8', (err, data) => {
      resolve(data);
    })
  })
}

readFile('./name.txt')
  .then(data => readFile(data))
  .then(data => readFile(data))
  .then(data => console.log(data));
```

`node`中有非常多的异步函数，写一个针对所有异步操作的函数。

```
function promisify(fn) {
  //收集函数执行的参数
  return function (...args) {
    return new Promise((resolve, reject) => {
      //执行原本的函数,且传入原本的参数以及要处理的最后的回调函数
      fn(...args, (err, data) => {
        //判断什么时候resolve/reject
        if (err) {
          reject(err);
        } else {
          resolve(data);
        }
      })
    })
  }
}

//调用
let readFile = promisify(fs.readFile);
readFile('./name.txt', 'utf-8')
  .then(data => readFile(data, 'utf-8'))
  .then(data => readFile(data, 'utf-8'))
  .then(data => console.log(data));
```

将`fs`模块上的所有方法转为`promisify`方法。

```
//格式:fs.writeFile => fs.writeFileAsync
function promisifyAll(obj) {
  for (let [key, fn] of Object.entries(obj)) {
    if (typeof fn === 'function') {
      obj[key + 'Async'] = promisify(fn);
    }
  }
}
```



